#!/usr/bin/env bash

# stuff created by configure.ac
rm -rf autom4te.cache/ 
rm -f Makefile.in aclocal.m4 configure depcomp install-sh missing compile test-driver
rm -f src/Makefile.in


# generated by configure
rm -f   Makefile config.log config.status
rm -rf  src/.deps/ src/Makefile
rm -f   src/test-suite.log src/test_cxxstats.log src/test_cxxstats.trs

# generated during make process
rm -f src/testcxxstats
